apiVersion: v1
kind: ServiceAccount
metadata:
  name: ktwin-twin-graph-store-sa
  namespace: ktwin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ktwin
  name: ktwin-twin-graph-store-role
rules:
- apiGroups: ["dtd.ktwin"]
  resources: ["twininstances"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ktwin-twin-graph-store-role-binding
  namespace: ktwin
subjects:
  - kind: ServiceAccount
    name: ktwin-twin-graph-store-sa
    namespace: ktwin
roleRef:
  kind: Role
  name: ktwin-twin-graph-store-role
  apiGroup: rbac.authorization.k8s.io