// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/twin-graph": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TwinGraphs"
                ],
                "summary": "Get Twin Graph",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.TwinGraph"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "This endpoint updates the latest TwinGraph.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TwinGraphs"
                ],
                "summary": "Update Twin Graph",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TwinGraph"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.TwinGraph": {
            "type": "object",
            "properties": {
                "twinInstances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TwinInstanceEnvironmentSettings"
                    }
                }
            }
        },
        "domain.TwinInstanceEnvironmentSettings": {
            "type": "object",
            "properties": {
                "interface": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TwinInstanceRelationshipSettings"
                    }
                }
            }
        },
        "domain.TwinInstanceRelationshipSettings": {
            "type": "object",
            "properties": {
                "instance": {
                    "type": "string"
                },
                "interface": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
