definitions:
  domain.TwinGraph:
    properties:
      twinInstances:
        items:
          $ref: '#/definitions/domain.TwinInstanceEnvironmentSettings'
        type: array
    type: object
  domain.TwinInstanceEnvironmentSettings:
    properties:
      interface:
        type: string
      name:
        type: string
      relationships:
        items:
          $ref: '#/definitions/domain.TwinInstanceRelationshipSettings'
        type: array
    type: object
  domain.TwinInstanceRelationshipSettings:
    properties:
      instance:
        type: string
      interface:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /twin-graph:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.TwinGraph'
            type: array
      summary: Get Twin Graph
      tags:
      - TwinGraphs
    post:
      consumes:
      - application/json
      description: This endpoint updates the latest TwinGraph.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TwinGraph'
      summary: Update Twin Graph
      tags:
      - TwinGraphs
swagger: "2.0"
